from PyQt5 import QtCore, QtGui, QtWidgets


class CustomLineEdit(QtWidgets.QLineEdit):
    clicked = QtCore.pyqtSignal()

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.clicked.emit()
        else:
            super().mousePressEvent(event)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 290)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(290, 290))
        MainWindow.setMaximumSize(QtCore.QSize(290, 290))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 291, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.mergeList = QtWidgets.QListWidget(self.tab)
        self.mergeList.setGeometry(QtCore.QRect(10, 41, 261, 181))
        self.mergeList.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mergeList.setObjectName("mergeList")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.label.setObjectName("label")
        self.mergeAdd = QtWidgets.QPushButton(self.tab)
        self.mergeAdd.setGeometry(QtCore.QRect(10, 230, 80, 21))
        self.mergeAdd.setObjectName("mergeAdd")
        self.mergeClear = QtWidgets.QPushButton(self.tab)
        self.mergeClear.setGeometry(QtCore.QRect(190, 10, 80, 21))
        self.mergeClear.setObjectName("mergeClear")
        self.mergeRun = QtWidgets.QPushButton(self.tab)
        self.mergeRun.setGeometry(QtCore.QRect(190, 230, 80, 21))
        self.mergeRun.setObjectName("mergeRun")
        self.mergeRemove = QtWidgets.QPushButton(self.tab)
        self.mergeRemove.setGeometry(QtCore.QRect(100, 230, 80, 21))
        self.mergeRemove.setObjectName("mergeRemove")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.splitType = QtWidgets.QComboBox(self.tab_2)
        self.splitType.setGeometry(QtCore.QRect(10, 200, 171, 22))
        self.splitType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitType.setObjectName("splitType")
        self.splitType.addItem("")
        self.splitType.addItem("")
        self.splitPage = QtWidgets.QSpinBox(self.tab_2)
        self.splitPage.setGeometry(QtCore.QRect(190, 200, 81, 22))
        self.splitPage.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.splitPage.setMaximum(32767)
        self.splitPage.setProperty("value", 1)
        self.splitPage.setObjectName("splitPage")
        self.splitLabel = QtWidgets.QLabel(self.tab_2)
        self.splitLabel.setGeometry(QtCore.QRect(190, 170, 81, 20))
        self.splitLabel.setObjectName("splitLabel")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.label_3.setObjectName("label_3")
        self.splitClear = QtWidgets.QPushButton(self.tab_2)
        self.splitClear.setGeometry(QtCore.QRect(190, 10, 80, 21))
        self.splitClear.setObjectName("splitClear")
        self.splitAdd = QtWidgets.QPushButton(self.tab_2)
        self.splitAdd.setGeometry(QtCore.QRect(10, 170, 80, 21))
        self.splitAdd.setObjectName("splitAdd")
        self.splitRemove = QtWidgets.QPushButton(self.tab_2)
        self.splitRemove.setGeometry(QtCore.QRect(100, 170, 80, 21))
        self.splitRemove.setObjectName("splitRemove")
        self.splitList = QtWidgets.QListWidget(self.tab_2)
        self.splitList.setGeometry(QtCore.QRect(10, 41, 261, 121))
        self.splitList.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.splitList.setUniformItemSizes(True)
        self.splitList.setWordWrap(True)
        self.splitList.setObjectName("splitList")
        self.splitRun = QtWidgets.QPushButton(self.tab_2)
        self.splitRun.setGeometry(QtCore.QRect(10, 230, 261, 21))
        self.splitRun.setObjectName("splitRun")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.watermarkRun = QtWidgets.QPushButton(self.tab_3)
        self.watermarkRun.setGeometry(QtCore.QRect(190, 170, 80, 21))
        self.watermarkRun.setObjectName("watermarkRun")
        self.watermarkAdd = QtWidgets.QPushButton(self.tab_3)
        self.watermarkAdd.setGeometry(QtCore.QRect(10, 170, 80, 21))
        self.watermarkAdd.setObjectName("watermarkAdd")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.label_4.setObjectName("label_4")
        self.watermarkClear = QtWidgets.QPushButton(self.tab_3)
        self.watermarkClear.setGeometry(QtCore.QRect(190, 10, 80, 21))
        self.watermarkClear.setObjectName("watermarkClear")
        self.watermarkList = QtWidgets.QListWidget(self.tab_3)
        self.watermarkList.setGeometry(QtCore.QRect(10, 41, 261, 121))
        self.watermarkList.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.watermarkList.setUniformItemSizes(True)
        self.watermarkList.setWordWrap(True)
        self.watermarkList.setObjectName("watermarkList")
        self.watermarkRemove = QtWidgets.QPushButton(self.tab_3)
        self.watermarkRemove.setGeometry(QtCore.QRect(100, 170, 80, 21))
        self.watermarkRemove.setObjectName("watermarkRemove")
        self.watermarkSelect = QtWidgets.QPushButton(self.tab_3)
        self.watermarkSelect.setGeometry(QtCore.QRect(10, 230, 261, 21))
        self.watermarkSelect.setObjectName("watermarkSelect")
        self.watermarkLabel = QtWidgets.QLabel(self.tab_3)
        self.watermarkLabel.setGeometry(QtCore.QRect(10, 200, 261, 21))
        self.watermarkLabel.setObjectName("watermarkLabel")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.label_5.setObjectName("label_5")
        self.encryptionClear = QtWidgets.QPushButton(self.tab_4)
        self.encryptionClear.setGeometry(QtCore.QRect(190, 10, 80, 21))
        self.encryptionClear.setObjectName("encryptionClear")
        self.encryptionEncrypt = QtWidgets.QPushButton(self.tab_4)
        self.encryptionEncrypt.setGeometry(QtCore.QRect(190, 170, 80, 21))
        self.encryptionEncrypt.setObjectName("encryptionEncrypt")
        self.encryptionRemove = QtWidgets.QPushButton(self.tab_4)
        self.encryptionRemove.setGeometry(QtCore.QRect(100, 170, 80, 21))
        self.encryptionRemove.setObjectName("encryptionRemove")
        self.encryptionList = QtWidgets.QListWidget(self.tab_4)
        self.encryptionList.setGeometry(QtCore.QRect(10, 41, 261, 121))
        self.encryptionList.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.encryptionList.setUniformItemSizes(True)
        self.encryptionList.setWordWrap(True)
        self.encryptionList.setObjectName("encryptionList")
        self.encryptionAdd = QtWidgets.QPushButton(self.tab_4)
        self.encryptionAdd.setGeometry(QtCore.QRect(10, 170, 80, 21))
        self.encryptionAdd.setObjectName("encryptionAdd")
        self.encryptionPassword = CustomLineEdit(self.tab_4)
        self.encryptionPassword.setGeometry(QtCore.QRect(10, 230, 171, 21))
        self.encryptionPassword.setObjectName("encryptionPassword")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 61, 16))
        self.label_2.setObjectName("label_2")
        self.encryptionDecrypt = QtWidgets.QPushButton(self.tab_4)
        self.encryptionDecrypt.setGeometry(QtCore.QRect(190, 200, 80, 21))
        self.encryptionDecrypt.setObjectName("encryptionDecrypt")
        self.encryptionRandom = QtWidgets.QPushButton(self.tab_4)
        self.encryptionRandom.setGeometry(QtCore.QRect(190, 230, 80, 21))
        self.encryptionRandom.setObjectName("encryptionRandom")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(70, 210, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "py-pdf-processor"))
        self.mergeList.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "Selected files:"))
        self.mergeAdd.setText(_translate("MainWindow", "Add"))
        self.mergeClear.setText(_translate("MainWindow", "Clear list"))
        self.mergeRun.setText(_translate("MainWindow", "Merge"))
        self.mergeRemove.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Merge")
        )
        self.splitType.setItemText(0, _translate("MainWindow", "Split all pages"))
        self.splitType.setItemText(
            1, _translate("MainWindow", "Split at specified page")
        )
        self.splitLabel.setText(_translate("MainWindow", "Split at page:"))
        self.label_3.setText(_translate("MainWindow", "Selected files:"))
        self.splitClear.setText(_translate("MainWindow", "Clear list"))
        self.splitAdd.setText(_translate("MainWindow", "Add"))
        self.splitRemove.setText(_translate("MainWindow", "Remove"))
        self.splitList.setSortingEnabled(True)
        self.splitRun.setText(_translate("MainWindow", "Split"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Split")
        )
        self.watermarkRun.setText(_translate("MainWindow", "Watermark"))
        self.watermarkAdd.setText(_translate("MainWindow", "Add"))
        self.label_4.setText(_translate("MainWindow", "Selected files:"))
        self.watermarkClear.setText(_translate("MainWindow", "Clear list"))
        self.watermarkList.setSortingEnabled(True)
        self.watermarkRemove.setText(_translate("MainWindow", "Remove"))
        self.watermarkSelect.setText(_translate("MainWindow", "Select Watermark PDF"))
        self.watermarkLabel.setText(
            _translate("MainWindow", "No watermark selected...")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Watermark")
        )
        self.label_5.setText(_translate("MainWindow", "Selected files:"))
        self.encryptionClear.setText(_translate("MainWindow", "Clear list"))
        self.encryptionEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.encryptionRemove.setText(_translate("MainWindow", "Remove"))
        self.encryptionList.setSortingEnabled(True)
        self.encryptionAdd.setText(_translate("MainWindow", "Add"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.encryptionDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.encryptionRandom.setText(_translate("MainWindow", "Random"))
        self.label_6.setText(_translate("MainWindow", "(click textbox to copy)"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Encryption")
        )
