name: build-linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyPDF2 PyQt6 wheel setuptools
      - name: Install libraries
        run: |
          sudo apt-get update && sudo apt-get install -y libqt5gui5
      - name: Build with pyinstaller
        run: |
          pyinstaller -F -w main.py
      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: py-pdf-processing-linux
          path: /home/runner/work/py-pdf-processing/py-pdf-processing/dist/main
